font_size 8
scrollback_lines 10000
background_opacity 0.82
cursor_trail 1

allow_remote_control yes
listen_on unix:/tmp/mykitty

# search scrollback buffer for keyword (vi-style)
map ctrl+shift+f show_scrollback

# maintain working directory in new tab or window
map ctrl+t launch --cwd=current --type=tab
map ctrl+n launch --cwd=current --type=os-window

# tmux-like window splitter
enabled_layouts splits
map ctrl+shift+d launch --cwd=current --location=hsplit
map ctrl+shift+s launch --cwd=current --location=vsplit
map ctrl+shift+r layout_action rotate

# move focus between split windows
map shift+left neighboring_window left
map shift+right neighboring_window right
map shift+up neighboring_window up
map shift+down neighboring_window down

# closing windows
map ctrl+shift+w close_window
map ctrl+alt+shift+w close_other_windows_in_tab

window_alert_on_bell yes
bell_on_tab "🔔 "

notify_on_cmd_finish invisible 5 notify-bell


# BEGIN_KITTY_FONTS
font_family      family="Liberation Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
