[General]
%2B8gcPZIuASRcihpYJW6UA83rPnH%2B7ifu11s9xp3p8Rc%23=1767694859
63tJmSFEpYg9dR34FZPBHK8VKGPcUT1yDVJWSS9UTuU%23=1767694859
GeoLocale=system
KXhiCZ2HpmjrAEVlAVyB4VHAVsfnyTQR06weNL9BKYY%23=1767694859
N65z0ERhK0hfZOUrpvZbKa20IAIu0Etuq8T%2BuqWl%2Bkw%23=1767694859
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
UeJ7AgrtBappnQjaaFui4jk8yVCY2K4zE14gyE34Rzo%23=1767694859
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=320
com.disable.connection.pk.status=false
com.zoom.client.langid=0
conf.webserver=https://zoom.us
conf.webserver.vendor.default=https://ucdavis.zoom.us
currentMeetingId=
deviceID=9C:65:EB:2F:0F:B2
disableCef=false
disableUsePasskey=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
isTransCoding=false
jK9BkbV8zNjw7whdX9AnddbmbOu4N8hVKwVt8iDnC38%23=1767694859
logLevel=info
newMeetingWithVideo=true
noSandbox=false
pOoALJyX%2BqjXWD3Cr1Q4lH5ZpVshFjYob0SH3xBr2jQ%23=1767694859
playSoundForNewMessage=false
shareBarTopMargin=0
shortcut_as_global_ShortcutID_Screenshot=false
shortcut_as_global_ShortcutID_ShowHideFloatingMeetingControls=true
showOneTimePTAICTipHubble=false
showOneTimeQueriesOptionTip=true
showOneTimeSmartRecognitionCoackMark=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=jdfeenstra@ucdavis.edu
webview.debug.enable=false
xwayland=true

[1VGa6fEsTQYEquYOdMv]
j1V5NQSTWNQPlSB8TSaIgvM%23=1767694859

[AS]
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[NT]
1ClfDkzjMbKRfgHNY04yBSDPqd0Uw2IE%2BhaiBTao%23=1767773376

[chat.recent]
recentlast.session=

[e2oewir4]
zlsEjhEtnrfV\1\RNfupD3GFHXnLPoOTzI%23=1767694859

[p2j01nOS5WVbsNRvQFnMTmH5SbwLdPoVQxAt]
B0jJHc%23=1767694859

[pvKc9SrvNy]
UrM6djKC7sBYYhjF2xNCSHVpXDpFealQ%23=1767694859

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="376,600"
main_frame_pixel_pos_wide="1280,960"
