font_family IntoneMono Nerd Font Mono
font_size 10
bold_font auto
italic_font auto
bold_italic_font auto
touch_scroll_multiplier 10.0

cursor #ff19fb
cursor_trail 1
cursor_trail_decay 0.5 0.8
cursor_trail_color #ff0000
cursor_shape block
cursor_text_color #000000
cursor_blink_interval 1
cursor_trail_start_threshold 1
cursor_beam_thickness 2.0
cursor_underline_thickness 2.0
cursor_stop_blinking_after 15.0
cursor_trail_decay 0.1 0.6

# search scrollback buffer for keyword (vi-mode)
map ctrl+shift+f show_scrollback

# ctrl + shift + t maintains working directory of previous session
map ctrl+shift+t launch --cwd=current --type=tab

enabled_layouts splits
# d for down below
map ctrl+shift+d launch --cwd=current --location=hsplit
# s for side by side
map ctrl+shift+s launch --cwd=current --location=vsplit
# rotate for confusion
map ctrl+shift+r layout_action rotate

# for moving focus between the split windows
map alt+shift+left neighboring_window left
map alt+shift+right neighboring_window right
map alt+shift+up neighboring_window up
map alt+shift+down neighboring_window down

# shell_integration no-cursor
background_opacity 0.85
background_blur 300
remember_window_size no
initial_window_width 1200
initial_window_height 800
enable_audio_bell no
window_padding_width 8
hide_window_decorations no
scrollback_lines 100000
dynamic_background_opacity yes
confirm_os_window_close 0
