general {
    lock_cmd = pidof hyprlock || hyprlock -c $HOME/.config/hypr/hyprlock.conf
    # lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}
### screen DIM
listener {
    timeout = 600 # 30 min
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
### LOCK screen
listener 
    timeout = 900 # 50 min
    on-timeout = loginctl lock-session
}

### screen OFF
listener {
    timeout = 1800 # 1800 hour
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
