directory: ~/music
library: ~/.config/beets/musiclibrary.db

import:
  copy: no  # Use files in place
  write: no # Don't modify tags

plugins:
  - musicbrainz # to fetch metadata
  - hook
  - export


# At the end of an import process, dump current state of library into version-controlled json file
hook:
  hooks:
    - event: cli_exit
      command: 'beet export -a -f json -o ~/.config/library.json'
