preload=/home/matt/.config/hypr/hyprpaper.d/screen1.png
preload=/home/matt/.config/hypr/hyprpaper.d/screen2.png
preload=/home/matt/.config/hypr/hyprpaper.d/screen3.png

wallpaper {
  monitor = DP-4
  path = /home/matt/.config/hypr/hyprpaper.d/screen1.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = /home/matt/.config/hypr/hyprpaper.d/screen2.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-5
  path = /home/matt/.config/hypr/hyprpaper.d/screen3.png
  fit_mode = cover
}
