monitor.bluez.properties = {
  bluez5.enable-sbc-xq        = true
  bluez5.enable-msbc          = true
  bluez5.a2dp.aac.bitratemode = 2
}

monitor.bluez.rules = [
  {
    matches = [ { device.name = "bluez_card.A4_77_58_5D_9A_CA" } ]
    actions = {
      update-props = {
        device.profile = "a2dp-sink"
      }
    }
  }
]
